const paymentActionTypes = {
    FETCH_ALL_PAYMENT:"FETCH_ALL_PAYMENT",
    FETCH_ALL_PAYMENT_FAIL:'FETCH_ALL_PAYMENT_FAIL',
    FETCH_ALL_PAYMENT_SUCCESS:"FETCH_ALL_PAYMENT_SUCCESS",

    FETCH_PAYMENT_BY_ID:"FETCH_PAYMENT_BY_ID",
    FETCH_PAYMENT_BY_ID_FAIL:'FETCH_PAYMENT_BY_ID_FAIL',
    FETCH_PAYMENT_BY_ID_SUCCESS:"FETCH_PAYMENT_BY_ID_SUCCESS",
}

export default paymentActionTypes;