const userActionTypes = {
    FETCH_ALL_USERS:"FETCH_ALL_USERS",
    FETCH_ALL_USERS_FAIL:'FETCH_ALL_USERS_FAIL',
    FETCH_ALL_USERS_SUCCESS:"FETCH_ALL_USERS_SUCCESS",

    FETCH_USER_BY_ID:"FETCH_USER_BY_ID",
    FETCH_USER_BY_ID_FAIL:'FETCH_USER_BY_ID_FAIL',
    FETCH_USER_BY_ID_SUCCESS:"FETCH_USER_BY_ID_SUCCESS",
}

export default userActionTypes;